// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maxh/gqlgen-todos/orm/ent/entityrevision"
	"github.com/maxh/gqlgen-todos/orm/ent/predicate"
)

// EntityRevisionDelete is the builder for deleting a EntityRevision entity.
type EntityRevisionDelete struct {
	config
	hooks    []Hook
	mutation *EntityRevisionMutation
}

// Where appends a list predicates to the EntityRevisionDelete builder.
func (erd *EntityRevisionDelete) Where(ps ...predicate.EntityRevision) *EntityRevisionDelete {
	erd.mutation.Where(ps...)
	return erd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (erd *EntityRevisionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(erd.hooks) == 0 {
		affected, err = erd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntityRevisionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			erd.mutation = mutation
			affected, err = erd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(erd.hooks) - 1; i >= 0; i-- {
			if erd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = erd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, erd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (erd *EntityRevisionDelete) ExecX(ctx context.Context) int {
	n, err := erd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (erd *EntityRevisionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: entityrevision.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: entityrevision.FieldID,
			},
		},
	}
	if ps := erd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, erd.driver, _spec)
}

// EntityRevisionDeleteOne is the builder for deleting a single EntityRevision entity.
type EntityRevisionDeleteOne struct {
	erd *EntityRevisionDelete
}

// Exec executes the deletion query.
func (erdo *EntityRevisionDeleteOne) Exec(ctx context.Context) error {
	n, err := erdo.erd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entityrevision.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (erdo *EntityRevisionDeleteOne) ExecX(ctx context.Context) {
	erdo.erd.ExecX(ctx)
}
