// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maxh/gqlgen-todos/nodevalue"
	"github.com/maxh/gqlgen-todos/orm/ent/noderevision"
	"github.com/maxh/gqlgen-todos/qid"
)

// NodeRevisionCreate is the builder for creating a NodeRevision entity.
type NodeRevisionCreate struct {
	config
	mutation *NodeRevisionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (nrc *NodeRevisionCreate) SetCreatedAt(t time.Time) *NodeRevisionCreate {
	nrc.mutation.SetCreatedAt(t)
	return nrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nrc *NodeRevisionCreate) SetNillableCreatedAt(t *time.Time) *NodeRevisionCreate {
	if t != nil {
		nrc.SetCreatedAt(*t)
	}
	return nrc
}

// SetCreatedBy sets the "created_by" field.
func (nrc *NodeRevisionCreate) SetCreatedBy(q qid.ID) *NodeRevisionCreate {
	nrc.mutation.SetCreatedBy(q)
	return nrc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (nrc *NodeRevisionCreate) SetNillableCreatedBy(q *qid.ID) *NodeRevisionCreate {
	if q != nil {
		nrc.SetCreatedBy(*q)
	}
	return nrc
}

// SetUpdatedAt sets the "updated_at" field.
func (nrc *NodeRevisionCreate) SetUpdatedAt(t time.Time) *NodeRevisionCreate {
	nrc.mutation.SetUpdatedAt(t)
	return nrc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nrc *NodeRevisionCreate) SetNillableUpdatedAt(t *time.Time) *NodeRevisionCreate {
	if t != nil {
		nrc.SetUpdatedAt(*t)
	}
	return nrc
}

// SetUpdatedBy sets the "updated_by" field.
func (nrc *NodeRevisionCreate) SetUpdatedBy(q qid.ID) *NodeRevisionCreate {
	nrc.mutation.SetUpdatedBy(q)
	return nrc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (nrc *NodeRevisionCreate) SetNillableUpdatedBy(q *qid.ID) *NodeRevisionCreate {
	if q != nil {
		nrc.SetUpdatedBy(*q)
	}
	return nrc
}

// SetNodeID sets the "node_id" field.
func (nrc *NodeRevisionCreate) SetNodeID(s string) *NodeRevisionCreate {
	nrc.mutation.SetNodeID(s)
	return nrc
}

// SetNodeRevision sets the "node_revision" field.
func (nrc *NodeRevisionCreate) SetNodeRevision(s string) *NodeRevisionCreate {
	nrc.mutation.SetNodeRevision(s)
	return nrc
}

// SetNodeValue sets the "node_value" field.
func (nrc *NodeRevisionCreate) SetNodeValue(nv *nodevalue.NodeValue) *NodeRevisionCreate {
	nrc.mutation.SetNodeValue(nv)
	return nrc
}

// SetID sets the "id" field.
func (nrc *NodeRevisionCreate) SetID(q qid.ID) *NodeRevisionCreate {
	nrc.mutation.SetID(q)
	return nrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (nrc *NodeRevisionCreate) SetNillableID(q *qid.ID) *NodeRevisionCreate {
	if q != nil {
		nrc.SetID(*q)
	}
	return nrc
}

// Mutation returns the NodeRevisionMutation object of the builder.
func (nrc *NodeRevisionCreate) Mutation() *NodeRevisionMutation {
	return nrc.mutation
}

// Save creates the NodeRevision in the database.
func (nrc *NodeRevisionCreate) Save(ctx context.Context) (*NodeRevision, error) {
	var (
		err  error
		node *NodeRevision
	)
	if err := nrc.defaults(); err != nil {
		return nil, err
	}
	if len(nrc.hooks) == 0 {
		if err = nrc.check(); err != nil {
			return nil, err
		}
		node, err = nrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NodeRevisionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nrc.check(); err != nil {
				return nil, err
			}
			nrc.mutation = mutation
			if node, err = nrc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(nrc.hooks) - 1; i >= 0; i-- {
			if nrc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nrc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nrc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nrc *NodeRevisionCreate) SaveX(ctx context.Context) *NodeRevision {
	v, err := nrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nrc *NodeRevisionCreate) Exec(ctx context.Context) error {
	_, err := nrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrc *NodeRevisionCreate) ExecX(ctx context.Context) {
	if err := nrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nrc *NodeRevisionCreate) defaults() error {
	if _, ok := nrc.mutation.CreatedAt(); !ok {
		if noderevision.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized noderevision.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := noderevision.DefaultCreatedAt()
		nrc.mutation.SetCreatedAt(v)
	}
	if _, ok := nrc.mutation.UpdatedAt(); !ok {
		if noderevision.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized noderevision.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := noderevision.DefaultUpdatedAt()
		nrc.mutation.SetUpdatedAt(v)
	}
	if _, ok := nrc.mutation.ID(); !ok {
		if noderevision.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized noderevision.DefaultID (forgotten import ent/runtime?)")
		}
		v := noderevision.DefaultID()
		nrc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (nrc *NodeRevisionCreate) check() error {
	if _, ok := nrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := nrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	if _, ok := nrc.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "node_id"`)}
	}
	if v, ok := nrc.mutation.NodeID(); ok {
		if err := noderevision.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "node_id": %w`, err)}
		}
	}
	if _, ok := nrc.mutation.NodeRevision(); !ok {
		return &ValidationError{Name: "node_revision", err: errors.New(`ent: missing required field "node_revision"`)}
	}
	if v, ok := nrc.mutation.NodeRevision(); ok {
		if err := noderevision.NodeRevisionValidator(v); err != nil {
			return &ValidationError{Name: "node_revision", err: fmt.Errorf(`ent: validator failed for field "node_revision": %w`, err)}
		}
	}
	if _, ok := nrc.mutation.NodeValue(); !ok {
		return &ValidationError{Name: "node_value", err: errors.New(`ent: missing required field "node_value"`)}
	}
	return nil
}

func (nrc *NodeRevisionCreate) sqlSave(ctx context.Context) (*NodeRevision, error) {
	_node, _spec := nrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(qid.ID)
	}
	return _node, nil
}

func (nrc *NodeRevisionCreate) createSpec() (*NodeRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &NodeRevision{config: nrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: noderevision.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: noderevision.FieldID,
			},
		}
	)
	if id, ok := nrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := nrc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: noderevision.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := nrc.mutation.CreatedBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: noderevision.FieldCreatedBy,
		})
		_node.CreatedBy = value
	}
	if value, ok := nrc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: noderevision.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := nrc.mutation.UpdatedBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: noderevision.FieldUpdatedBy,
		})
		_node.UpdatedBy = value
	}
	if value, ok := nrc.mutation.NodeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: noderevision.FieldNodeID,
		})
		_node.NodeID = value
	}
	if value, ok := nrc.mutation.NodeRevision(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: noderevision.FieldNodeRevision,
		})
		_node.NodeRevision = value
	}
	if value, ok := nrc.mutation.NodeValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: noderevision.FieldNodeValue,
		})
		_node.NodeValue = value
	}
	return _node, _spec
}

// NodeRevisionCreateBulk is the builder for creating many NodeRevision entities in bulk.
type NodeRevisionCreateBulk struct {
	config
	builders []*NodeRevisionCreate
}

// Save creates the NodeRevision entities in the database.
func (nrcb *NodeRevisionCreateBulk) Save(ctx context.Context) ([]*NodeRevision, error) {
	specs := make([]*sqlgraph.CreateSpec, len(nrcb.builders))
	nodes := make([]*NodeRevision, len(nrcb.builders))
	mutators := make([]Mutator, len(nrcb.builders))
	for i := range nrcb.builders {
		func(i int, root context.Context) {
			builder := nrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nrcb *NodeRevisionCreateBulk) SaveX(ctx context.Context) []*NodeRevision {
	v, err := nrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nrcb *NodeRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := nrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrcb *NodeRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := nrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
