// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maxh/gqlgen-todos/orm/ent/noderevision"
	"github.com/maxh/gqlgen-todos/orm/ent/predicate"
)

// NodeRevisionDelete is the builder for deleting a NodeRevision entity.
type NodeRevisionDelete struct {
	config
	hooks    []Hook
	mutation *NodeRevisionMutation
}

// Where appends a list predicates to the NodeRevisionDelete builder.
func (nrd *NodeRevisionDelete) Where(ps ...predicate.NodeRevision) *NodeRevisionDelete {
	nrd.mutation.Where(ps...)
	return nrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nrd *NodeRevisionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nrd.hooks) == 0 {
		affected, err = nrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NodeRevisionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nrd.mutation = mutation
			affected, err = nrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nrd.hooks) - 1; i >= 0; i-- {
			if nrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrd *NodeRevisionDelete) ExecX(ctx context.Context) int {
	n, err := nrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nrd *NodeRevisionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: noderevision.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: noderevision.FieldID,
			},
		},
	}
	if ps := nrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, nrd.driver, _spec)
}

// NodeRevisionDeleteOne is the builder for deleting a single NodeRevision entity.
type NodeRevisionDeleteOne struct {
	nrd *NodeRevisionDelete
}

// Exec executes the deletion query.
func (nrdo *NodeRevisionDeleteOne) Exec(ctx context.Context) error {
	n, err := nrdo.nrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{noderevision.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nrdo *NodeRevisionDeleteOne) ExecX(ctx context.Context) {
	nrdo.nrd.ExecX(ctx)
}
