// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"github.com/maxh/gqlgen-todos/qid"
)

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID qid.ID `json:"userId"`
}
