// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"github.com/maxh/gqlgen-todos/orm/schema/pulid"
)

type CreateTodoInput struct {
	Text   string   `json:"text"`
	UserID pulid.ID `json:"userId"`
}
